#!/usr/bin/env python3
"""Mint the disclosed-synthetic voice presets that ship with a Llasa bundle.

Llasa needs no reference audio: prompted with text alone it invents a speaker per
call, so two calls never sound like the same person. A preset pins one down — it
records the transcript of a generated utterance together with the XCodec2 codes
the model emitted for it, and later calls replay those codes as an in-context
prompt so generation continues that speaker.

The codes therefore come straight out of the model; nothing is encoded, and no
recording of a real person is involved. Every preset in ``voices.json`` is
machine-generated and marked ``"synthetic": true``.

Usage::

    python make_presets.py --bundle out/bundle/llasa-1b-onnx --output voices.json
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np

#: Seed utterances. The text is what the preset's transcript will be, so it has to
#: be a natural, fully punctuated sentence in the preset's language; the seed picks
#: which speaker the model invents.
SEEDS = [
    ("en_female_a", "en", 11,
     "The morning light came through the kitchen window, and the whole house smelled of coffee."),
    ("en_male_a", "en", 23,
     "I told him the road was closed, but he wanted to see it for himself."),
    ("zh_female_a", "zh", 5,
     "今天天气很好，我们一起去公园散步吧。"),
    ("zh_male_a", "zh", 17,
     "他说这件事情并不复杂，只是需要一点耐心。"),
]


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--bundle", required=True)
    ap.add_argument("--output", required=True)
    ap.add_argument("--wav-dir", default=None, help="also write each preset's audio here")
    ap.add_argument("--default", default=SEEDS[0][0])
    args = ap.parse_args()

    import soundfile as sf
    from phoonnx.config import SynthesisConfig
    from phoonnx.voice import TTSVoice

    bundle = Path(args.bundle)
    voice = TTSVoice.load(
        str(bundle / "model.onnx"),
        config_path=str(bundle / "config.json"),
        engine_params={
            "codec_decoder_path": str(bundle / "xcodec2_decoder.onnx"),
            "tokenizer_path": str(bundle / "tokenizer.json"),
        },
    )
    adapter = voice.adapter

    presets = {}
    for name, lang, seed, text in SEEDS:
        prompt_ids = adapter.encode_text(text, voice, None)[0]
        rng = np.random.default_rng(seed)
        token_ids = adapter.generate(voice.session, prompt_ids,
                                     adapter.default_params(), rng)
        codes = adapter.token_ids_to_codes(token_ids)
        audio = adapter.decode_codes(codes)
        print(f"{name}: {len(codes)} codes, {len(audio) / 16000:.2f}s", flush=True)
        if args.wav_dir:
            Path(args.wav_dir).mkdir(parents=True, exist_ok=True)
            sf.write(str(Path(args.wav_dir) / f"{name}.wav"), audio, 16000)
        presets[name] = {
            "text": text,
            "lang": lang,
            "codes": codes,
            "synthetic": True,
            "seed": seed,
        }

    doc = {
        "default_voice": args.default,
        "note": ("Every preset here was generated by the model itself from text alone "
                 "and is not a recording of any person."),
        "presets": presets,
    }
    Path(args.output).write_text(json.dumps(doc, ensure_ascii=False, indent=2))
    print("wrote", args.output)


if __name__ == "__main__":
    main()
